#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

main() {
  local package elm_dir
  package="$*"
  elm_dir="client/src/elm"

  elm_package_install_in_dir "$package" "$elm_dir"
  elm_package_install_in_dir "$package" "$elm_dir/tests"
}

elm_package_install_in_dir() {
  local package
  package="$1"
  shift

  (
  cd_to_git_root
  cd "$@"
  elm-package install --yes "$package"
  )
}

cd_to_git_root() {
  cd "$(git rev-parse --show-toplevel)"
}


main "$@"
